services:
  redis:
    image: redis
    ports:
      - 6379:6379 
  mariadb:
    image: mariadb:10.6
    volumes:
      - c:/data/mysql:/var/lib/mysql
    ports:
      - 3306:3306 
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  redisinsight:
    image: redis/redisinsight
    ports:
      - 8081:5540    
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=123456